language: node_js

node_js:
  - "12"
  - "11"
  - "10"
  - "8"

services:
  - mysql
  - mongodb

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test; USE test; CREATE TABLE `users` (`id` int(11) NOT NULL AUTO_INCREMENT,`firstName` varchar(100) DEFAULT NULL,`lastName` varchar(100) DEFAULT NULL,`username` varchar(100) DEFAULT NULL,PRIMARY KEY (`id`)) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8;'

notifications:
  email:
    on_success: never
    on_failure: always
